@extends(''admin.layout.layout'')

@section(''admin-title'')
    Reports
@endsection

@section(''admin-content'')
<div class="admin-page-section">
    <div class="page-header">
        <h1>Reports</h1>
        <p class="page-subtitle">Generate and review operational reports</p>
    </div>

    <div class="quick-stats-grid">
        @include(''admin.ticket-analytics.components.stat-card'', [
            ''title'' => ''Total Reports'',
            ''value'' => $totalReports ?? 0,
            ''icon'' => ''📋'',
            ''trend'' => ''generated'',
            ''color'' => ''primary''
        ])
        
        @include(''admin.ticket-analytics.components.stat-card'', [
            ''title'' => ''This Month'',
            ''value'' => $thisMonth ?? 0,
            ''icon'' => ''📅'',
            ''trend'' => ''reports'',
            ''color'' => ''info''
        ])
        
        @include(''admin.ticket-analytics.components.stat-card'', [
            ''title'' => ''This Year'',
            ''value'' => $thisYear ?? 0,
            ''icon'' => ''📊'',
            ''trend'' => ''total'',
            ''color'' => ''success''
        ])
    </div>

    <section class="table-section">
        <h2 class="section-title">Recent Reports</h2>
        <div class="table-wrapper">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Report Name</th>
                        <th>Type</th>
                        <th>Period</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reports ?? [] as $report)
                        <tr>
                            <td><strong>{{ $report[''name''] ?? ''Report'' }}</strong></td>
                            <td>{{ ucfirst($report[''type''] ?? ''summary'') }}</td>
                            <td>{{ $report[''period''] ?? ''N/A'' }}</td>
                            <td>{{ $report[''generated_by''] ?? ''System'' }}</td>
                            <td>{{ $report[''date''] ?? ''N/A'' }}</td>
                            <td class="actions">
                                <button class="action-btn">View</button>
                                <button class="action-btn">Download</button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </section>
</div>

<style>
.admin-page-section { max-width: 1200px; margin: 0 auto; }
.page-header { margin-bottom: 2rem; }
.page-header h1 { font-size: 1.75rem; font-weight: 700; margin: 0 0 0.5rem 0; }
.page-subtitle { font-size: 0.95rem; color: #666; margin: 0; }
.section-title { font-size: 1.1rem; font-weight: 600; margin-bottom: 1.5rem; }
.quick-stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
.table-section { background: white; border-radius: 8px; padding: 1.5rem; }
.table-wrapper { border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }
.data-table { width: 100%; border-collapse: collapse; }
.data-table th { background-color: #f5f5f5; padding: 1rem; text-align: left; font-weight: 600; color: #333; border-bottom: 2px solid #e0e0e0; }
.data-table td { padding: 1rem; border-bottom: 1px solid #e0e0e0; }
.data-table tbody tr:hover { background-color: #f9f9f9; }
.actions { display: flex; gap: 0.5rem; }
.action-btn { padding: 0.4rem 0.8rem; border: 1px solid #ddd; background: white; border-radius: 4px; cursor: pointer; font-weight: 600; font-size: 0.8rem; transition: all 0.3s ease; }
.action-btn:hover { border-color: #2196F3; color: #2196F3; }
</style>
@endsection
